// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsBxX-92ddoJa8lLRyI14XvsFUS56vhB0',
    appId: '1:1737450578:web:7bba8411b88d72fb2c6b8b',
    messagingSenderId: '1737450578',
    projectId: 'wydatki-81e67',
    authDomain: 'wydatki-81e67.firebaseapp.com',
    storageBucket: 'wydatki-81e67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TL-13Z20X5TuMS_rZVCueftVT3dYMDY',
    appId: '1:1737450578:android:8f039f9a4030c3732c6b8b',
    messagingSenderId: '1737450578',
    projectId: 'wydatki-81e67',
    storageBucket: 'wydatki-81e67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMxywaj7QUHs3dMDyfh6_RPOx0ZtSLjvc',
    appId: '1:1737450578:ios:04efb0627ceaa83c2c6b8b',
    messagingSenderId: '1737450578',
    projectId: 'wydatki-81e67',
    storageBucket: 'wydatki-81e67.appspot.com',
    iosClientId: '1737450578-8efph5rpcvvsei6hv1phhclv0pl1t1rl.apps.googleusercontent.com',
    iosBundleId: 'com.jaroslawcielecki.pizza',
  );
}
